name: CI

on:
  pull_request:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "templates/**"
      - "Cargo.*"

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast
